//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cesium.Ion.Revit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cesium.Ion.Revit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Authorization Denied!&lt;/h2&gt;.
        /// </summary>
        internal static string AuthDeniedHTML {
            get {
                return ResourceManager.GetString("AuthDeniedHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Authorization Complete!&lt;/span&gt;&lt;h3&gt;Return to Revit to begin your export!&lt;/h3&gt;.
        /// </summary>
        internal static string AuthSucceedHTML {
            get {
                return ResourceManager.GetString("AuthSucceedHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cesium16 {
            get {
                object obj = ResourceManager.GetObject("Cesium16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cesium32 {
            get {
                object obj = ResourceManager.GetObject("Cesium32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be in 3D view to export..
        /// </summary>
        internal static string ErrorViewportDescription {
            get {
                return ResourceManager.GetString("ErrorViewportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed!.
        /// </summary>
        internal static string ErrorViewportTitle {
            get {
                return ResourceManager.GetString("ErrorViewportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources and tutorials for how to use Cesium ion in Revit.
        /// </summary>
        internal static string HelpButtonDescription {
            get {
                return ResourceManager.GetString("HelpButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpButtonLabel {
            get {
                return ResourceManager.GetString("HelpButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.cesium.com/.
        /// </summary>
        internal static string IonAPIURL {
            get {
                return ResourceManager.GetString("IonAPIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42.
        /// </summary>
        internal static string IonClientID {
            get {
                return ResourceManager.GetString("IonClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10101.
        /// </summary>
        internal static string IonRedirectPort {
            get {
                return ResourceManager.GetString("IonRedirectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cesium.com/ion/.
        /// </summary>
        internal static string IonURL {
            get {
                return ResourceManager.GetString("IonURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize your Cesium ion account for Revit.
        /// </summary>
        internal static string LoginButtonDescription {
            get {
                return ResourceManager.GetString("LoginButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string LoginButtonLabel {
            get {
                return ResourceManager.GetString("LoginButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove your Cesium ion account from Revit.
        /// </summary>
        internal static string LogoutButtonDescription {
            get {
                return ResourceManager.GetString("LogoutButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string LogoutButtonLabel {
            get {
                return ResourceManager.GetString("LogoutButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesium ion.
        /// </summary>
        internal static string RibbonLabel {
            get {
                return ResourceManager.GetString("RibbonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share and tile your Revit model in Cesium ion.
        /// </summary>
        internal static string UploadButtonDescription {
            get {
                return ResourceManager.GetString("UploadButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string UploadButtonLabel {
            get {
                return ResourceManager.GetString("UploadButtonLabel", resourceCulture);
            }
        }
    }
}
